# Generated by Django 4.1.5 on 2023-01-21 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=30)),
        ),
    ]
