# Generated by Django 4.1.5 on 2023-01-22 01:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_flashcard_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generate_room_code, max_length=6, unique=True),
        ),
    ]
