# Generated by Django 4.1.5 on 2023-01-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(null=False, default=30),
        ),
    ]
