# Generated by Django 4.1.5 on 2023-01-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='round_time_limit',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
