# Generated by Django 4.1.5 on 2023-01-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_room_max_players_alter_room_round_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='round_time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
