# Generated by Django 4.1.5 on 2023-01-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_room_max_players_alter_room_round_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='quiz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='api.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.room')),
            ],
        ),
    ]
